import os
import markdown
from xhtml2pdf import pisa
from datetime import datetime

class PDFReportGenerator:
    def __init__(self, output_dir: str = "artifacts/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_audit_report(self, query: str, content: str, map_images: list = None) -> str:
        filename = f"ClimateX_Audit_{int(datetime.now().timestamp())}.pdf"
        filepath = os.path.join(self.output_dir, filename)

        # 1. Convert Markdown Content to HTML
        html_content = markdown.markdown(content, extensions=['extra', 'codehilite', 'tables'])

        # 2. Build Image HTML
        images_html = ""
        if map_images:
            images_html += "<div class='evidence-section'><h2>Visual Evidence (Truth Layer)</h2>"
            for img_path in map_images:
                # xhtml2pdf requires local paths or full URLs. 
                # Absolute paths work best.
                abs_path = os.path.abspath(img_path)
                images_html += f"""
                <div class='evidence-card'>
                    <img src='{abs_path}' class='evidence-img' />
                    <p class='caption'>Source: Real-time Fire/Satellite Data ({os.path.basename(img_path)})</p>
                </div>
                """
            images_html += "</div>"

        # 3. Construct Full HTML Document with CSS (The "Beautiful" part)
        full_html = f"""
        <html>
        <head>
            <style>
                @page {{
                    size: A4;
                    margin: 2cm;
                }}
                body {{
                    font-family: 'Helvetica', sans-serif;
                    color: #1e293b;
                    line-height: 1.6;
                }}
                .header {{
                    text-align: center;
                    border-bottom: 2px solid #06b6d4; /* Cyan */
                    padding-bottom: 20px;
                    margin-bottom: 30px;
                }}
                h1.title {{
                    color: #0f172a; /* Slate 900 */
                    font-size: 24pt;
                    margin: 0;
                }}
                .meta {{
                    color: #64748b;
                    font-size: 10pt;
                    margin-top: 5px;
                }}
                .risk-scorecard {{
                    background-color: #f8fafc;
                    border: 1px solid #e2e8f0;
                    border-radius: 8px;
                    padding: 15px;
                    margin: 20px 0;
                }}
                .risk-title {{
                    color: #06b6d4;
                    font-size: 14pt;
                    font-weight: bold;
                    margin-bottom: 10px;
                    border-bottom: 1px solid #e2e8f0;
                    padding-bottom: 5px;
                }}
                /* Markdown Content Styling */
                h1 {{ color: #0f172a; font-size: 18pt; margin-top: 20px; border-bottom: 1px solid #e2e8f0; }}
                h2 {{ color: #334155; font-size: 15pt; margin-top: 15px; }}
                h3 {{ color: #475569; font-size: 13pt; margin-top: 10px; }}
                p {{ margin-bottom: 10px; text-align: justify; }}
                ul {{ margin-left: 20px; margin-bottom: 10px; }}
                li {{ margin-bottom: 5px; }}
                strong {{ color: #0f172a; font-weight: bold; }}
                
                /* Evidence Styling */
                .evidence-section {{ page-break-before: always; }}
                .evidence-card {{ 
                    margin-bottom: 20px; 
                    text-align: center;
                    border: 1px solid #ddd;
                    padding: 10px;
                    background-color: #fff;
                }}
                .evidence-img {{ 
                    width: 100%; 
                    height: auto; 
                }}
                .caption {{
                    font-size: 9pt;
                    color: #64748b;
                    margin-top: 5px;
                    font-style: italic;
                }}
                .footer {{
                    position: fixed;
                    bottom: 0;
                    left: 0;
                    right: 0;
                    height: 50px;
                    text-align: center;
                    font-size: 8pt;
                    color: #94a3b8;
                    border-top: 1px solid #e2e8f0;
                    padding-top: 10px;
                }}
            </style>
        </head>
        <body>
            <div class='header'>
                <h1 class='title'>CARBON AUDIT REPORT</h1>
                <p class='meta'>Project: {query} | Generated by ClimateX.ai</p>
            </div>

            <div class='risk-scorecard'>
                <div class='risk-title'>EXECUTIVE RISK SUMMARY</div>
                <p><strong>Verification Status:</strong> PENDING REVIEW</p>
                <p>This automated report synthesizes Deep Research (textual analysis) with real-time Satellite Truth Layer data (NASA FIRMS) to verify carbon offset integrity.</p>
            </div>

            <div class='content'>
                {html_content}
            </div>

            {images_html}

            <div class='footer'>
                ClimateX.ai Confidential Audit • ISO 14064 Compliant • Generated on {datetime.now().strftime('%Y-%m-%d')}
            </div>
        </body>
        </html>
        """

        # 4. Write PDF
        with open(filepath, "wb") as pdf_file:
            pisa_status = pisa.CreatePDF(full_html, dest=pdf_file)

        if pisa_status.err:
            raise Exception(f"PDF generation error: {pisa_status.err}")

        return os.path.abspath(filepath)
